package com.comp602project.comp602projectbackend.portfolio;

import java.util.List;

public class PortfolioSuggestionsResponse {

    private List<String> skills;
    private List<ProjectSuggestion> projects;
    /** "ai" when generated by Groq, "curated" when using built-in suggestions */
    private String source;

    public PortfolioSuggestionsResponse() {}

    public PortfolioSuggestionsResponse(List<String> skills, List<ProjectSuggestion> projects, String source) {
        this.skills = skills;
        this.projects = projects;
        this.source = source;
    }

    public List<String> getSkills() { return skills; }
    public void setSkills(List<String> skills) { this.skills = skills; }

    public List<ProjectSuggestion> getProjects() { return projects; }
    public void setProjects(List<ProjectSuggestion> projects) { this.projects = projects; }

    public String getSource() { return source; }
    public void setSource(String source) { this.source = source; }
}
