spring.application.name=comp602-project-backend
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?prepareThreshold=0

spring.datasource.username=postgres.xszwcrgudblvfglddruy
#SET THIS PRIVATE WHEN WE MAKE OUR REPO PUBLIC!!
spring.datasource.password=C0nn3ctly*78z

# Automatically creates tables from @Entity classes on first run, updates them if you add new fields
spring.jpa.hibernate.ddl-auto=update

# Tells Spring Boot you are using PostgreSQL so it generates the correct SQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Prints every SQL query Spring runs to the console, for debugging, remove later
spring.jpa.show-sql=true

spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false